### ISSUE TITLE
MAKE CHECK: [Makefile:588: check-recursive] Error 1

### ISSUE THREAD

**Issue by AleNovelli** [ketiltrout/getdata#2]
Hello,

I am having some difficulties upgrading to version `0.11.0` of `libgetdata++7`.
I am trying to upgrade to this version because of the [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=992437) regarding dirfiles that affects also KST.

After I download `getdata-0.11.0.tar.gz` I can run `./configure` and `make` whithout any errors.
However when i run `make check` this error comes up:
```
make getdata-clean-dirs
make[5]: Entering directory '/home/lspe/xinstall/getdata-0.11.0/bindings/cxx/test'
rm -rf *odirfile
make[5]: Leaving directory '/home/lspe/xinstall/getdata-0.11.0/bindings/cxx/test'
make[4]: Leaving directory '/home/lspe/xinstall/getdata-0.11.0/bindings/cxx/test'
make[3]: Leaving directory '/home/lspe/xinstall/getdata-0.11.0/bindings/cxx/test'
make[3]: Entering directory '/home/lspe/xinstall/getdata-0.11.0/bindings/cxx'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/home/lspe/xinstall/getdata-0.11.0/bindings/cxx'
make[2]: Leaving directory '/home/lspe/xinstall/getdata-0.11.0/bindings/cxx'
Making check in perl
make[2]: Entering directory '/home/lspe/xinstall/getdata-0.11.0/bindings/perl'
export LD_LIBRARY_PATH=../../../src/.libs: && \
	( cd build && make test  )
make[3]: Entering directory '/home/lspe/xinstall/getdata-0.11.0/bindings/perl/build'
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- GetData.bs blib/arch/auto/GetData/GetData.bs 644
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/big_test.t .. Died at t/big_test.t line 153.
# Looks like your test exited with 13 before it could output anything.
t/big_test.t .. Dubious, test returned 13 (wstat 3328, 0xd00)
Failed 1766/1766 subtests 
t/callback.t .. 1/8 
#   Failed test at t/callback.t line 41.
Died at t/callback.t line 43.
# Looks like your test exited with 2 just after 1.
t/callback.t .. Dubious, test returned 2 (wstat 512, 0x200)
Failed 8/8 subtests 

Test Summary Report
-------------------
t/big_test.t (Wstat: 3328 Tests: 0 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 1766 tests but ran 0.
t/callback.t (Wstat: 512 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 8 tests but ran 1.
Files=2, Tests=1,  1 wallclock secs ( 0.07 usr  0.03 sys +  0.53 cusr  0.08 csys =  0.71 CPU)
Result: FAIL
Failed 2/2 test programs. 1/1 subtests failed.
make[3]: *** [Makefile:1017: test_dynamic] Error 2
make[3]: Leaving directory '/home/lspe/xinstall/getdata-0.11.0/bindings/perl/build'
make[2]: *** [Makefile:830: check] Error 2
make[2]: Leaving directory '/home/lspe/xinstall/getdata-0.11.0/bindings/perl'
make[1]: *** [Makefile:584: check-recursive] Error 1
make[1]: Leaving directory '/home/lspe/xinstall/getdata-0.11.0/bindings'
make: *** [Makefile:588: check-recursive] Error 1
```

Do you have any idea what causes this?
Alternatively i could roll back to version `0.10.0-9` which worked fine but the apt package manager does not find this version and online I can't fin any other easy way to roll back to this version.

Thanks for your help

**Comment by ketiltrout** [comment]
What version of Perl are you using?

**Comment by ketiltrout** [comment]
Can you also provide your `config.log` file?

**Comment by AleNovelli** [comment]
This is the version of Perl that i am running

`This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-gnu-thread-multi
(with 47 registered patches, see perl -V for more detail)`

And this is the [config.log](https://github.com/ketiltrout/getdata/files/7632788/config.log) file.

**Comment by ketiltrout** [comment]
It looks like the perl tests are failing to create the test dirfiles.  Do you perhaps not have write access to the perl `build` directory that the tests are running in ( `home/lspe/xinstall/getdata-0.11.0/bindings/perl/build` )?

**Comment by AleNovelli** [comment]
I attempted to repeat the process both running `./config` as sudo and also running the whole process as superuser but it gives me the same error and it seems to me that also the [new config.log](https://github.com/ketiltrout/getdata/files/7650868/config.log) is almost the same.

**Comment by ketiltrout** [comment]
Okay.  Try applying this patch (or else just use master, where I've pushed it).  All it does is print some error messages when I/O errors occur instead of just exiting.  It's not going to fix the problem but it might help us figure out what's going on.
[printdies.diff.txt](https://github.com/ketiltrout/getdata/files/7671537/printdies.diff.txt)

**Comment by AleNovelli** [comment]
I cloned the master branch an repeated the process. 
Here is the [config.log](https://github.com/ketiltrout/getdata/files/7694061/config.log) file and here is the new error message.
Thank you

```
make[4]: Entering directory '/home/lspe/xinstall/getdata/bindings/cxx/test'
PASS: big_test
=============
1 test passed
=============
make getdata-clean-dirs
make[5]: Entering directory '/home/lspe/xinstall/getdata/bindings/cxx/test'
rm -rf *odirfile
make[5]: Leaving directory '/home/lspe/xinstall/getdata/bindings/cxx/test'
make[4]: Leaving directory '/home/lspe/xinstall/getdata/bindings/cxx/test'
make[3]: Leaving directory '/home/lspe/xinstall/getdata/bindings/cxx/test'
make[3]: Entering directory '/home/lspe/xinstall/getdata/bindings/cxx'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/home/lspe/xinstall/getdata/bindings/cxx'
make[2]: Leaving directory '/home/lspe/xinstall/getdata/bindings/cxx'
Making check in perl
make[2]: Entering directory '/home/lspe/xinstall/getdata/bindings/perl'
export LD_LIBRARY_PATH=../../../src/.libs: && \
	( cd build && make test  )
make[3]: Entering directory '/home/lspe/xinstall/getdata/bindings/perl/build'
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- GetData.bs blib/arch/auto/GetData/GetData.bs 644
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/big_test.t .. Unable to create dirfile: Permission denied at t/big_test.t line 153.
# Looks like your test exited with 13 before it could output anything.
t/big_test.t .. Dubious, test returned 13 (wstat 3328, 0xd00)
Failed 1766/1766 subtests 
t/callback.t .. 1/8 
#   Failed test at t/callback.t line 40.
Unable to create format file: No such file or directory at t/callback.t line 42.
# Looks like your test exited with 2 just after 1.
t/callback.t .. Dubious, test returned 2 (wstat 512, 0x200)
Failed 8/8 subtests 

Test Summary Report
-------------------
t/big_test.t (Wstat: 3328 Tests: 0 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 1766 tests but ran 0.
t/callback.t (Wstat: 512 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 8 tests but ran 1.
Files=2, Tests=1,  1 wallclock secs ( 0.08 usr  0.02 sys +  0.53 cusr  0.08 csys =  0.71 CPU)
Result: FAIL
Failed 2/2 test programs. 1/1 subtests failed.
make[3]: *** [Makefile:1017: test_dynamic] Error 2
make[3]: Leaving directory '/home/lspe/xinstall/getdata/bindings/perl/build'
make[2]: *** [Makefile:831: check] Error 2
make[2]: Leaving directory '/home/lspe/xinstall/getdata/bindings/perl'
make[1]: *** [Makefile:585: check-recursive] Error 1
make[1]: Leaving directory '/home/lspe/xinstall/getdata/bindings'
make: *** [Makefile:591: check-recursive] Error 1
[2]+  Done                    gedit config.log
```

**Comment by ketiltrout** [comment]
Yeah, that's what I thought was happening:
> t/big_test.t .. Unable to create dirfile: Permission denied at t/big_test.t line 153.

There's a permissions problem of some kind on your filesystem.  I don't know what could be causing that.  The build system doesn't mess around with directory permissions itself.

I wish I could be more help, but I don't know what might be going on.  Some weird filesystem thing?  ACLs?  Angering SELinux?  If you have a sysadmin for this machine, you might want to ask them for some advice.

My only recommendation, which I think you've already done would have been to try creating an entirely new copy of the GetData sources by extracting the release tarball somewhere else and try there, in case, the current build tree had gotten into a weird state.

I've tried compiling GetData from both release tarballs (`.gz` and `.xz`) as well as the GitHub-generated "source code" archive and I'm unable to reproduce your problem.

What distro are you doing this on?
