### ISSUE TITLE
Build failure on macOS

### ISSUE THREAD

**Issue by carlocab** [ketiltrout/getdata#5]
We're trying to update Homebrew's version of libgetdata at Homebrew/homebrew-core#94532. We're encountering the following build failure:
```
  Making install in perl
  /Applications/Xcode.app/Contents/Developer/usr/bin/make  install-exec-hook
  install_name_tool -change \
  		/private/tmp/libgetdata-20220207-11042-1evf59w/getdata-0.11.0/src/.libs/libgetdata.9.dylib \
  		/usr/local/Cellar/libgetdata/0.11.0/lib/libgetdata.9.dylib \
  		/usr/local/Cellar/libgetdata/0.11.0/lib/perl/5.18.4/auto/GetData/GetData.bundle
  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /usr/local/Cellar/libgetdata/0.11.0/lib/perl/5.18.4/auto/GetData/GetData.bundle (No such file or directory)
```
My guess is that it's trying to call `install_name_tool` on `GetData.bundle` inside the install prefix before `GetData.bundle` has been installed.

This occurs on every version of macOS that we're able to build for: 10.15, 11, and 12, both Intel and ARM (where applicable).

Logs available at https://github.com/Homebrew/homebrew-core/actions/runs/1805821533, and the error (on macOS 10.15) starts at https://github.com/Homebrew/homebrew-core/runs/5091763175?check_suite_focus=true#step:6:998.

We invoke `configure` as
```
./configure --prefix=/usr/local/Cellar/libgetdata/0.11.0 --disable-dependency-tracking --disable-silent-rules --disable-fortran --disable-fortran95 --disable-php --disable-python --without-liblzma --without-libzzip
```
and then call `make && make install`.

Any assistance would be appreciated.

**Comment by carlocab** [comment]
#4 is probably related.

**Comment by ketiltrout** [comment]
I can reproduce this locally, and have a fix that seems much too simple for it (and is different than #6 ), but now I'm trying to figure out under what conditions this problem manifests.
